In [11]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(np.arange(10))

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
a.ndim

1

In [13]:
a.shape

(3,)

In [14]:
len(a)

3

In [15]:
import numpy as np
b = np.array([[2,3,4], [2,35,34]])
b

array([[ 2,  3,  4],
       [ 2, 35, 34]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
len(b)

2

In [19]:
c = np.array([[[1,2,3],[4,5,6]],[[3,4,7],[4,5,6]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 7],
        [4, 5, 6]]])

In [20]:
c.shape

(2, 2, 3)

In [21]:
len(c)

2

# fuctions of array


In [34]:
a = np.arange(1,50,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [50]:
a = np.linspace(1, 5, 5)
#this is used to divide the range in particular segments
a

array([1., 2., 3., 4., 5.])

In [58]:
c = np.ones((3,4))*9
c

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [62]:
a = np.eye(6,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [63]:
a = np.diag([1,2,3,4,5,6,7])
a

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [72]:
a = np.random.rand(4)
a

array([0.27816675, 0.37102852, 0.43519975, 0.55908526])

# Basis data types